In [0]:
!cal            

    January 2020      
Su Mo Tu We Th Fr Sa  
          1  2  3  4  
 5  6  7  8  9 10 11  
12 13 14 15 16 17 18  
19 20 21 22 23 24 25  
26 27 28 29 30 31     
                      


In [0]:
!cat /etc/issue    #for checking OS name


Ubuntu 18.04.3 LTS \n \l



In [0]:
!free -m          #for checking RAM in MB


              total        used        free      shared  buff/cache   available
Mem:          13022         515       10593           0        1913       12236
Swap:             0           0           0


In [0]:
!lscpu             #for CPU check

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2300.000
BogoMIPS:            4600.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs 

In [0]:
# We are going to use Numpy
# pip install numpy    to install in local labs
import numpy as np

In [0]:
#len(dir(np))
#lets create 1D array
a1=np.array([2,6,76,8])

In [0]:
#creating 2D array
x=np.array([[2,6,7],[3,5,9],[6,9,5],[3,11,2]])

In [0]:
x

array([[ 2,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
# to print 1st row
  x[0]

array([2, 6, 7])

In [0]:
# to print 1st element of 2D array
   x[0][0]

2

In [0]:
# to print first two row
x[0:2]

array([[2, 6, 7],
       [3, 5, 9]])

In [0]:
# to print 1st column
x[0:,0]

array([2, 3, 6, 3])

In [0]:
# to print 1st two columns
x[0:,0:2]

array([[ 2,  6],
       [ 3,  5],
       [ 6,  9],
       [ 3, 11]])

In [0]:
# task
x[1:3,1:]

array([[5, 9],
       [9, 5]])

In [0]:
# next task
x[1:3,[0,2]]

array([[3, 9],
       [6, 5]])

In [0]:
# Final task
x[1::2,[0,2]]

array([[3, 9],
       [3, 2]])

In [0]:
# Math ops
x

array([[ 2,  6,  7],
       [ 3,  5,  9],
       [ 6,  9,  5],
       [ 3, 11,  2]])

In [0]:
x+6

array([[ 8, 12, 13],
       [ 9, 11, 15],
       [12, 15, 11],
       [ 9, 17,  8]])

In [0]:
y=x+6
y

array([[ 8, 12, 13],
       [ 9, 11, 15],
       [12, 15, 11],
       [ 9, 17,  8]])

In [0]:
x+y

array([[10, 18, 20],
       [12, 16, 24],
       [18, 24, 16],
       [12, 28, 10]])

In [0]:
x**2

array([[  4,  36,  49],
       [  9,  25,  81],
       [ 36,  81,  25],
       [  9, 121,   4]])

In [0]:
x**3

array([[   8,  216,  343],
       [  27,  125,  729],
       [ 216,  729,  125],
       [  27, 1331,    8]])

In [0]:
#final about numpy
# 10 7 with all zeroes
np.zeros((10,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [0]:
#ones
np.ones((10,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [1]:
np.full((12,5),7)

NameError: ignored